dataset :
  hdf5_file: "/projects/pnria/caroline/pair_saxs_les_closest_of_concentration.h5"
  pad_size: 80
  material: ["ag"]
  conversion_dict_path: "/projects/pnria/caroline/conversion_dict_all.json"
  sample_frac: 1.0
  batch_size: 32
  num_workers: 3
  to_normalize : ['data_y_saxs','data_y_les']

training :
  num_gpus : 1
  num_nodes : 1
  num_epochs : 50

  lambda_param : 0.0001
  weight_latent_similarity : 0.1
  weight_kld_saxs : 0.00001
  weight_kld_les : 0.00001
  weight_saxs2saxs : 0.1
  weight_saxs2les : 1
  weight_les2les : 1
  weight_les2saxs : 0.1

  max_lr : 0.001
  T_max : 15
  eta_min : 0.000001

model :
  VAE_SAXS :
    vae_class : CustomizableVAE
    path_checkpoint : "/projects/pnria/julien/autofill/runs_v2/saxs_ag_gpu1/version_0/checkpoints/vae-epoch=62-val_loss=0.00001.ckpt"
    path_config : "/projects/pnria/julien/autofill/runs_v2/saxs_ag_gpu1/version_0/hparams.yaml"
    args :
      in_channels: 1
      output_channels: 1
      input_dim : 80
      latent_dim : 64 
      down_channels: [32, 64, 128]
      up_channels: [128, 64, 32]
      strat: "y"

  VAE_LES :
    vae_class : CustomizableVAE
    path_checkpoint : "/projects/pnria/julien/autofill/runs_v2/les_ag_gpu1/version_0/checkpoints/vae-epoch=10-val_loss=0.00006.ckpt"
    path_config : "/projects/pnria/julien/autofill/runs_v2/les_ag_gpu1/version_0/hparams.yaml"
    args :
      in_channels: 1
      output_channels: 1
      input_dim : 80
      latent_dim : 64 
      down_channels: [32, 64, 128]
      up_channels: [128, 64, 32]
      strat: "y"