dataset :
  hdf5_file: "pair_saxs_les_closest_of_concentration.h5"
  pad_size: 80
  material: ["ag"]
  conversion_dict_path: "conversion_dict_all.json"
  sample_frac: 1.0
  batch_size: 32
  num_workers: 3

training :
  num_gpus : 1
  num_nodes : 1
  num_epochs : 50

  lambda_param : 0.0001
  weight_latent_similarity : 0.1
  weight_kld_saxs : 0.0001
  weight_kld_les : 0.0001
  weight_saxs2saxs : 1
  weight_saxs2les : 1
  weight_les2les : 1
  weight_les2saxs : 1

  max_lr : 0.0001
  T_max : 10
  eta_min : 0.00001

model :
  VAE_SAXS :
    vae_class :
    path_checkpoint : /projects/pnria/julien/autofill/runs/saxs_ag_gpu1/version_0/checkpoints/vae-epoch=27-val_loss=0.00042.ckpt
    path_config : /projects/pnria/julien/autofill/runs/saxs_ag_gpu1/version_1/hparams.yaml
    args :
      in_channels: 1
      out_channels: 1
      down_channels: [32, 64, 128]
      up_channels: [128, 64, 32]
      down_rate: [2, 2, 2]
      up_rate: [2, 2, 2]
      cross_attention_dim: 16
      strat: "y"

  VAE_LES :
    vae_class :
    path_checkpoint : /projects/pnria/julien/autofill/runs/les_ag_gpu1/version_0/checkpoints/vae-epoch=49-val_loss=0.00024.ckpt
    path_config : /projects/pnria/julien/autofill/runs/les_ag_gpu1/version_1/hparams.yaml
    args :
      in_channels: 1
      out_channels: 1
      down_channels: [32, 64, 128]
      up_channels: [128, 64, 32]
      down_rate: [2, 2, 2]
      up_rate: [2, 2, 2]
      cross_attention_dim: 16
      strat: "y"