experiment_name: "AUTOFILL_LES"
run_name: les_cylinder
mlflow_uri: https://mlflowts.irit.fr/
dataset:
  conversion_dict: /projects/pnria/DATA/AUTOFILL/v2/all_data_v2.json
  hdf5_file: /projects/pnria/DATA/AUTOFILL/v2/all_data_v2.h5
  metadata_filters:
    material:
    - ag
    shape:
    - cylinder
    technique:
    - les
    type:
    - simulation
  requested_metadata:
  - shape
  - material
  sample_frac: 1.0
transforms_data:
  y:
    PreprocessingLES:
      pad_size: 500
  q:
    PreprocessingQ:
      pad_size: 500

training:
  T_max: 100
  batch_size: 128
  beta: 1.0e-05
  eta_min: 1.0e-08
  max_lr: 1.0e-04
  num_epochs: 300
  num_gpus: 1
  num_nodes: 1
  num_workers: 1
  patience: 40
  use_loglog: false
  min_delta: 0.00001

model:
  vae_class: ResVAEBN
  args:
    in_channels: 1
    output_channels: 1
    dilation: 1
    input_dim: 500
    latent_dim: 128
    down_channels: [8, 16, 32, 64, 128, 256 ]
    up_channels: [ 256, 128, 64, 32, 16, 8]
    strat: "y"

param_grid:
  model.args.latent_dim: [ 128, 64 ]    