convertion_dict:
  material:
    ag: 0
    au: 1
    latex: 2
    silica: 3
    sio2: 4
  method:
    chemsaxs: 1
    pysaxs: 0
  shape:
    cube: 3
    cylinder: 0
    cylindre triangle: 2
    parallelepipede: 4
    sphere: 1
  technique:
    les: 0
    saxs: 1
  type:
    experimental: 1
    simulation: 0
dataset:
  conversion_dict: /projects/pnria/DATA/AUTOFILL/v2/all_data_v2.json
  hdf5_file: /projects/pnria/DATA/AUTOFILL/v2/all_data_v2.h5
  metadata_filters:
    material:
    - ag
    shape:
    - cylinder
    technique:
    - saxs
    type:
    - simulation
  requested_metadata:
  - shape
  - material
  sample_frac: 1.0
experiment_name: AUTOFILL_SAXS
mlflow_uri: https://mlflowts.irit.fr/
model:
  args:
    dilation: 1
    down_channels:
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    in_channels: 1
    input_dim: 500
    latent_dim: 128
    output_channels: 1
    strat: y
    up_channels:
    - 256
    - 128
    - 64
    - 32
    - 16
    - 8
  type: vae
  vae_class: ResVAEBN
run_name: saxs_cylinder
training:
  T_max: 150
  batch_size: 16
  beta: 1.0e-06
  eta_min: 1.0e-08
  every_n_epochs: 10
  max_lr: 0.0001
  num_epochs: 600
  num_gpus: 1
  num_nodes: 1
  num_samples: 10
  num_workers: 8
  patience: 60
  plot_train: true
  save_every: 1
  use_loglog: true

transforms_data:
  y:
    PreprocessingSAXS:
      pad_size: 500
  q:
    PreprocessingQ:
      pad_size: 500


param_grid:
  model.args.latent_dim: [ 128, 64 ]
  training.batch_size: [ 16, 32, 64, 128 ]