
log_dir: run_c
beta : 0.0001
num_gpus : 1
num_nodes : 1
num_epochs : 50
max_lr : 0.0001
T_max : 10
eta_min : 0.00001
max_epochs: 100
batch_size: 128
patience: 10

dataset :
  hdf5_file: "/projects/pnria/julien/autofill/all_data.h5"
  pad_size: 80
  material: ["ag"]
  technique : ["saxs"]
  conversion_dict_path: "/projects/pnria/julien/autofill/conversion_dict_all.json"
  sample_frac: 1.0
  num_workers: 3
  to_normalize : ['data_y']


model :
  vae_class : CustomizableVAE
  in_channels: 1
  output_channels: 1
  input_dim : 80
  latent_dim : 64
  down_channels: [32, 64, 128]
  up_channels: [128, 64, 32]
  strat: "y"
  beta: 0.00001
  learning_rate: 0.0001
  max_lr : 0.0001
  T_max : 10
  eta_min : 0.00001

