dataset :
  hdf5_file: "/projects/pnria/julien/autofill/all_data.h5"
  pad_size: 80
  material: ["ag"]
  technique : ["saxs"]
  conversion_dict_path: "/projects/pnria/julien/autofill/conversion_dict_all.json"
  sample_frac: 1.0
  batch_size: 32
  num_workers: 3
  to_normalize : ['data_y']

training :
  beta : 0.0001
  num_gpus : 1
  num_nodes : 1
  num_epochs : 50

  max_lr : 0.0001
  T_max : 10
  eta_min : 0.00001

model :
  vae_class : CustomizableVAE
  args :
    in_channels: 1
    output_channels: 1
    input_dim : 80
    latent_dim : 64 
    down_channels: [32, 64, 128]
    up_channels: [128, 64, 32]
    strat: "y"

