dataset :
  hdf5_file: "/projects/pnria/julien/autofill/all_data.h5"
  metadata_filters :
    material: ["ag"]
    technique : ["les"]
    type : ["simulation"]
  requested_metadata : ["shape", "material"]
  conversion_dict_path: "/projects/pnria/julien/autofill/conversion_dict_all.json"
  sample_frac: 1.0
  transform : 
    y :
      MinMaxNormalizer: {}
      PaddingTransformer:
        pad_size : 80
        value : 0
    q :
      PaddingTransformer:
        pad_size: 80
        value: 0

training : 
  num_gpus : 1
  num_nodes : 1
  num_epochs : 300
  patience : 30

  batch_size: 64
  num_workers: 3

  beta: 0.005

  max_lr : 0.0001
  T_max : 75
  eta_min : 0.0000001
  
model :
  vae_class : ResVAE
  output_transform_log : False
  args :
      in_channels: 1
      output_channels: 1
      dilation : 1
      input_dim : 80
      latent_dim : 64
      down_channels: [64, 128, 256]
      up_channels: [256, 128, 64]
      strat: "y"
  
